GET http://localhost:5050/posts?page=1

####
POST http://localhost:5050/posts/create HTTP/1.1
Content-Type: application/json

{
  "title": "POST con referencing",
  "category": "Categoria uno",
  "cover": "https://static.vecteezy.com/system/resources/thumbnails/000/192/818/small/T_3-01.jpg",
  "price": 36,
  "rate": 5,
  "author": "651ef391ff31868b54c994a9"
}

####
PATCH http://localhost:5050/posts/update/6515b673381148d20b34c4a0
Content-Type: application/json

{
  "title": "Primo post MODIFICATO",
  "category": "Categoria MODIFICATA",
  "rate": 546545
}

####
DELETE http://localhost:5050/posts/delete/6515b673381148d20b34c4a0

####
GET http://localhost:5050/posts/bytitle?title=ti

###
GET http://localhost:5050/posts/bydate/2022-09-28

####
POST http://localhost:5050/users/create HTTP/1.1
Content-Type: application/json

{
  "firstName": "Gianni",
  "lastName": "Verdi",
  "email": "ciao@gmail.com",
  "password": "65465465464"
}

####
POST http://localhost:5050/send-email HTTP/1.1
Content-Type: application/json

{
  "subject": "email confidenziale",
  "text": "Salve questa è una email."
}